# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import upload_window as uw
import live_translator as lt

import Libraries.userdetails as userdetails


class Ui_login_window(object):

    def open_window(self, val):
        # # 1 for live window
        # # 2 for non live window
        # # 3 for login
        if val == 1:
            self.MainWindow = QtWidgets.QMainWindow()
            self.MainWindow.setWindowTitle("Translate+")
            self.ui = lt.Ui_MainWindow()
            self.ui.setupUi(self.MainWindow)
            self.MainWindow.show()

        elif val == 2:
            self.UploadWindow = QtWidgets.QMainWindow()
            self.UploadWindow.setWindowTitle("Translate+")

            self.ui = uw.Ui_UploadWindow()

            self.ui.setupUi(self.UploadWindow)

            self.UploadWindow.show()

    def setupUi(self, login_screen):
        login_screen.setObjectName("login_window")
        login_screen.resize(347, 452)

        login_screen.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.centralwidget = QtWidgets.QWidget(login_screen)
        self.centralwidget.setObjectName("centralwidget")

        self.password_ico = QtWidgets.QLabel(self.centralwidget)
        self.password_ico.setGeometry(QtCore.QRect(40, 270, 31, 30))
        self.password_ico.setText("")
        self.password_ico.setPixmap(
            QtGui.QPixmap("images/password_img.png"))
        self.password_ico.setScaledContents(True)
        self.password_ico.setObjectName("password_ico")

        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(120, 370, 121, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.login_button.setFont(font)
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("QPushButton {\n"
                                        "   font-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\n"
                                        "color : white;\n"
                                        "background-color: #4CAF50;\n"
                                        "border-radius: 2px;\n"
                                        "border: 2px solid #4CAF50;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: white;\n"
                                        "    color: black;\n"
                                        "}\n"
                                        "")
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")

        self.user_ico = QtWidgets.QLabel(self.centralwidget)
        self.user_ico.setGeometry(QtCore.QRect(40, 210, 31, 30))
        self.user_ico.setText("")
        self.user_ico.setPixmap(QtGui.QPixmap("images/user_img.png"))
        self.user_ico.setScaledContents(True)
        self.user_ico.setObjectName("user_ico")

        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(110, 90, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        font.setItalic(True)
        self.login_label.setFont(font)
        self.login_label.setTextFormat(QtCore.Qt.AutoText)
        self.login_label.setScaledContents(False)
        self.login_label.setObjectName("login_label")

        self.stay_signed = QtWidgets.QCheckBox(self.centralwidget)
        self.stay_signed.setGeometry(QtCore.QRect(40, 320, 127, 25))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setItalic(False)
        self.stay_signed.setFont(font)
        self.stay_signed.setObjectName("stay_signed")

        self.password_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.password_entry.setGeometry(QtCore.QRect(80, 270, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setItalic(False)
        self.password_entry.setFont(font)
        self.password_entry.setAutoFillBackground(False)
        self.password_entry.setStyleSheet("")
        self.password_entry.setInputMask("")
        self.password_entry.setText("")
        self.password_entry.setDragEnabled(False)
        self.password_entry.setObjectName("password_entry")

        self.username_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.username_entry.setGeometry(QtCore.QRect(80, 210, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setItalic(False)
        self.username_entry.setFont(font)
        self.username_entry.setAutoFillBackground(False)
        self.username_entry.setStyleSheet("")
        self.username_entry.setInputMask("")
        self.username_entry.setText("")
        self.username_entry.setDragEnabled(False)
        self.username_entry.setObjectName("username_entry")

        self.hor_line_2 = QtWidgets.QFrame(self.centralwidget)
        self.hor_line_2.setGeometry(QtCore.QRect(30, 300, 291, 12))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.hor_line_2.setFont(font)
        self.hor_line_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.hor_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_2.setObjectName("hor_line_2")

        self.hor_line1 = QtWidgets.QFrame(self.centralwidget)
        self.hor_line1.setGeometry(QtCore.QRect(30, 240, 291, 12))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.hor_line1.setFont(font)
        self.hor_line1.setStyleSheet("color: rgb(0, 0, 0);")
        self.hor_line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line1.setObjectName("hor_line1")

        self.mode_frame = QtWidgets.QFrame(self.centralwidget)
        self.mode_frame.setEnabled(True)
        self.mode_frame.setGeometry(QtCore.QRect(20, 50, 311, 381))
        self.mode_frame.setAutoFillBackground(False)
        self.mode_frame.setStyleSheet("QFrame#mode_frame {\n"
                                      "    border: 2px solid rgb(249, 225, 255);\n"
                                      "    selection-color: rgb(255, 249, 249);\n"
                                      "}")
        self.mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mode_frame.setObjectName("mode_frame")

        self.mode_frame.setVisible(False)

        self.use_label = QtWidgets.QLabel(self.mode_frame)
        self.use_label.setGeometry(QtCore.QRect(30, 10, 251, 141))

        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        font.setItalic(True)
        self.use_label.setFont(font)
        self.use_label.setTextFormat(QtCore.Qt.AutoText)
        self.use_label.setScaledContents(False)
        self.use_label.setObjectName("use_label")
        self.live_button = QtWidgets.QPushButton(self.mode_frame)
        self.live_button.setGeometry(QtCore.QRect(90, 190, 121, 51))

        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.live_button.setFont(font)
        self.live_button.setAutoFillBackground(False)
        self.live_button.setStyleSheet("QPushButton {\n"
                                       "   font-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\n"
                                       "color : white;\n"
                                       "background-color: #4CAF50;\n"
                                       "border-radius: 2px;\n"
                                       "border: 2px solid #4CAF50;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: white;\n"
                                       "    color: black;\n"
                                       "}\n"
                                       "")
        self.live_button.setFlat(False)
        self.live_button.setObjectName("live_button")

        self.upload_button = QtWidgets.QPushButton(self.mode_frame)
        self.upload_button.setGeometry(QtCore.QRect(90, 280, 121, 51))

        font = QtGui.QFont()
        font.setFamily("HelveticaNeue-Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.upload_button.setFont(font)
        self.upload_button.setAutoFillBackground(False)
        self.upload_button.setStyleSheet("QPushButton {\n"
                                         "   font-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\n"
                                         "color : white;\n"
                                         "background-color: #4CAF50;\n"
                                         "border-radius: 2px;\n"
                                         "border: 2px solid #4CAF50;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: white;\n"
                                         "    color: black;\n"
                                         "}\n"
                                         "")
        self.upload_button.setFlat(False)
        self.upload_button.setObjectName("upload_button")
        login_screen.setCentralWidget(self.centralwidget)

        self.login_button.clicked.connect(self.show_mode_frame)

        self.live_button.clicked.connect(lambda: self.open_window(1))
        self.live_button.clicked.connect(login_screen.close)

        self.upload_button.clicked.connect(lambda: self.open_window(2))
        self.upload_button.clicked.connect(login_screen.close)
        self.retranslateUi(login_screen)

        QtCore.QMetaObject.connectSlotsByName(login_screen)

    def show_mode_frame(self):

        if (self.password_entry.text() != ""):
            userdetails.directory = self.password_entry.text()
        if (self.username_entry.text() != ""):
            userdetails.filename = self.username_entry.text()
        # userdetails.show_user_details()
        self.mode_frame.setVisible(True)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "MainWindow"))
        self.login_button.setText(_translate("login_window", "Login"))
        self.login_label.setText(_translate(
            "login_window", "<html><head/><body><p align=\"center\">Login</p></body></html>"))
        self.stay_signed.setText(_translate("login_window", "Stay signed in"))
        self.password_entry.setPlaceholderText(
            _translate("login_window", "Nickname"))
        self.username_entry.setPlaceholderText(
            _translate("login_window", "Username"))
        self.use_label.setText(_translate(
            "login_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">How would you like </span></p><p align=\"center\"><span style=\" font-size:14pt;\">to use it?</span></p></body></html>"))
        self.live_button.setText(_translate("login_window", "Live"))
        self.upload_button.setText(_translate("login_window", "Upload"))
